services:

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    network_mode: host
    volumes:
      - ./backend/app/database/duckdb:/backend/app/database/duckdb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
