apiVersion: v1
kind: Pod
metadata:
  name: pg-proxy
spec:
  containers:
  - name: socat
    image: alpine/socat
    args:
      - TCP-LISTEN:5432,fork
      - TCP:postgresql-cnpg-112794-rw.user-lucasrt.svc.cluster.local:5432